### ISSUE TITLE
Рефактор Card/Game

### ISSUE THREAD

**Issue by standy66** [LenaAn/TrumpStamp#12]
Сейчас часть анимаций для карты создается и вызывается в Card, часть в Game. Нужно перенести все анимации в Card. Методы, создающие анимации пусть называются _build_*_anim. Снаружи карта должна иметь только логические методы - drop, use, которые внутри должны создавать и строить соответствующие анимации.

**Comment by GreenRiverRUS** [comment]
Плюнул в душу :) Но вообще, согласен, там не оч

**Comment by standy66** [comment]
Мне кажется вообще будет классно, если вся графика и анимация будет внутри Card, а наружу будут торчать только логические методы. @AliakseiSemchankau так просил
